from distutils.core import setup

setup(name='haizea',
      version='0.9',
      description='Haizea',
      author='University of Chicago',
      author_email='borja@cs.uchicago.edu',
      url='http://haizea.cs.uchicago.edu/',
      package_dir = {'': 'src'},
      packages=['haizea', 
                'haizea.cli',
                'haizea.common', 
                'haizea.core', 
                'haizea.core.scheduler',
                'haizea.core.scheduler.preparation_schedulers',
                'haizea.core.enact',
                'haizea.core.frontends',
                'haizea.policies'],
      scripts=['bin/haizea', 'bin/haizea-generate-configs', 'bin/haizea-generate-scripts', 'bin/haizea-convert-data', 
               'bin/haizea-cancel-lease', 'bin/haizea-list-leases', 'bin/haizea-list-hosts', 'bin/haizea-request-lease',
               'bin/haizea-show-queue'],
      data_files=[('share/haizea/etc', ['etc/sample_trace.conf', 
                          'etc/sample_opennebula.conf',
                          'etc/sample_multi.conf',
                          'etc/condor.template',
                          'etc/run.sh.template']),
                  ('share/haizea/traces', ['traces/sample.lwf',
                             'traces/sample.images']),
                  ('share/haizea/traces/multi', ['traces/multi/inj1.lwf',
                                                 'traces/multi/inj2.lwf',
                                                 'traces/multi/withprematureend.lwf',
                                                 'traces/multi/withoutprematureend.lwf']),
                  ],
      classifiers=[
          'Development Status :: 4 - Beta',
          'Environment :: Console',
          'Environment :: No Input/Output (Daemon)',
          'Intended Audience :: Developers',
          'Intended Audience :: System Administrators',
          'License :: OSI Approved :: Apache Software License',
          'Operating System :: POSIX',
          'Programming Language :: Python',
          'Topic :: Scientific/Engineering',
          'Topic :: System :: Distributed Computing'
          ]
     )
