from distutils.core import setup

setup(name='haizea',
      version='TP1.0',
      description='Haizea',
      author='University of Chicago',
      author_email='borja@cs.uchicago.edu',
      url='http://haizea.cs.uchicago.edu/',
      package_dir = {'': 'src'},
      packages=['haizea', 
                'haizea.common', 
                'haizea.resourcemanager',
                'haizea.resourcemanager.deployment',
                'haizea.resourcemanager.enact',
                'haizea.resourcemanager.enact.shared',
                'haizea.resourcemanager.enact.simulated',
                'haizea.resourcemanager.enact.opennebula',
                'haizea.resourcemanager.frontends',
                'haizea.traces'],
      scripts=['bin/haizea', 'bin/haizea-generate-configs', 'bin/haizea-generate-scripts', 'bin/haizea-convert-data'],
      data_files=[('share/haizea/etc', ['etc/sample.conf', 
                          'etc/sample_opennebula.conf',
                          'etc/sample_multi.conf',
                          'etc/condor.template',
                          'etc/run.sh.template']),
                  ('share/haizea/traces', ['traces/sample.lwf',
                             'traces/sample_opennebula.lwf',
                             'traces/sample.images']),
                  ('share/haizea/traces/multi', ['traces/multi/inj1.lwf',
                                                 'traces/multi/inj2.lwf',
                                                 'traces/multi/withprematureend.lwf',
                                                 'traces/multi/withoutprematureend.lwf']),
                  ],
      classifiers=[
          'Development Status :: 2 - Pre-Alpha',
          'Environment :: Console',
          'Environment :: No Input/Output (Daemon)',
          'Intended Audience :: Developers',
          'Intended Audience :: System Administrators',
          'License :: OSI Approved :: Apache Software License',
          'Operating System :: POSIX',
          'Programming Language :: Python',
          'Topic :: Scientific/Engineering',
          'Topic :: System :: Distributed Computing'
          ]
     )
