BEGIN TRANSACTION;
INSERT INTO "TB_SLOT_TYPE" VALUES(1, 'CPU');
INSERT INTO "TB_SLOT_TYPE" VALUES(2, 'Memory');
INSERT INTO "TB_SLOT_TYPE" VALUES(3, 'Inbound network');
INSERT INTO "TB_SLOT_TYPE" VALUES(4, 'Outbound network');
INSERT INTO "TB_RESPART_TYPE" VALUES(1, 'VM');
INSERT INTO "TB_RESPART_TYPE" VALUES(2, 'Overhead (Image transfer)');
COMMIT;